kannel_settings:
   host: xxxxxxxxxx
   port: 13000
   username: admin
   password: xxxxxxx
   smsc_to_be_skipped:
    - smsc1
    - smsc3
   kannel_name: 'TEST-KANNEL'
email_settings:
   to: 'eshaiju@gmail.com'
   from: 'notification@kannle.in'



