kannel_settings:
   host: xxxxxxxxxx
   port: 13000
   username: admin
   password: xxxxxxx
   smsc_to_be_skipped:
    - VfirstTranscriticalESMS
    - RouteSmsTransaction
   kannel_name: 'FA-KANNEL'
email_settings:
   to: 'shaiju@mobme.in'
   from: 'notification@kannle.in'



